### ISSUE TITLE
Add LICENSE file or a section in README

### ISSUE THREAD

**Issue by ifraixedes** [PlasmaPower/assert-request#3]
Please consider to make the license more clear adding a LICENSE file at the root of the repo or mentioning it in a "license" section in the README.

I know that `package.json` has it, but I think that one of those solutions would make it very visible.

Thanks for the module and release it under MIT

**Comment by PlasmaPower** [comment]
Good idea! I've added the license file. I meant to add it earlier, but it would appear I forgot.
