### ISSUE TITLE
Support async assertions

### ISSUE THREAD

**Issue by domarmstrong** [PlasmaPower/assert-request#4]
This is supported by supertest

```
request.get('/foo').assert(res => myPromiseAssertion(res))
```

Should be a simple change to something like:

```
'use strict';

const assert = require('assert');

module.exports = {
  assert: function (fn) {
    return this.then(function (res) {
      return Promise.resolve(fn(res))
        .then(value => assert(value))
        .then(() => res);
    });
  }
};
```

**Comment by PlasmaPower** [comment]
Currently you can do:

``` js
request.get('/foo')
  .then(res => { assert(myPromiseAssertion(res); return res })
```

Is that sufficient? I planned assertions to be more of a quick check. I could add a .run that doesn't touch the return value if you'd like.

**Comment by domarmstrong** [comment]
Actually a .run would suit my case much better. I'm normally running some assertions in a function that may throw errors (sometimes async assertions), but don't have a truthy return value so I have to do things like this:

```
    await request
      .get('/analytics/socials')
      .assert(res => {
        Joi.assert(res.body.data, Joi.array().items({
          posts: Joi.number().integer(),
        }));
        return true;
      });
```

```
    await request
      .get('/analytics/socials')
      .run(res => {
        Joi.assert(res.body.data, Joi.array().items({
          posts: Joi.number().integer(),
        }));
      });
```

I appreciate I can just use the return value of the request, but it is nice and clean. When running a series of requests its nice and easy to see the assertions attached to the request.

**Comment by PlasmaPower** [comment]
I figured as much. I'll make that mixin later today when I get a chance, it shouldn't be too hard.
