### ISSUE TITLE
Request header support

### ISSUE THREAD

**Issue by tomsun** [PlasmaPower/assert-request#5]
Is it possible to set request headers somehow?

With superagent and supertest you use `.set()`
https://github.com/visionmedia/supertest/blame/d0c14578cd51eab83019ee7d5a46d21a2ae5b170/Readme.md#L48-L60

`TypeError: AssertRequest(...).post(...).set is not a function`
`TypeError: AssertRequest(...).set is not a function`

( `assert-request@1.0.6` )

**Comment by PlasmaPower** [comment]
You can pass them as a separate parameter to the request function, as this internally uses request-promise.

**Comment by motet-a** [comment]
This works fine:

```js
const assertRequest = require('assert-request')(app)

function myRequest(path, options = {}) {
    return assertRequest(path, {
        headers: {
            'Content-Type': 'application/json',
        },

        ...options,
    })
}
```

**Comment by PlasmaPower** [comment]
Yep, pretty much that. By the time the assertRequest call is finished, the request is already sent (by design). I don't have plans to change that.
